version: '3'
services:
  jenkins-blueocean:
    image: myjenkins-blueocean:2.384-jdk17
    networks:
      - jenkins
    restart: on-failure
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - publish 8080:8080
      - publish 50000:50000
    volumes:
    - jenkins-data:/var/jenkins_home
    - volume jenkins-docker-certs:/certs/client:ro

volumes:
  - jenkins-data
  - jenkins-docker-certs
networks:
  - jenkins:
    external: true

# docker run \
#   --name jenkins-blueocean \
#   --restart=on-failure \
#   --detach \
#   --network jenkins \
#   --env DOCKER_HOST=tcp://docker:2376 \
#   --env DOCKER_CERT_PATH=/certs/client \
#   --env DOCKER_TLS_VERIFY=1 \
#   --publish 8080:8080 \
#   --publish 50000:50000 \
#   --volume jenkins-data:/var/jenkins_home \
#   --volume jenkins-docker-certs:/certs/client:ro \
#   myjenkins-blueocean:2.375.1-1 